version: "3.9"

services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres_local
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backups:/backups

volumes:
    postgres_data:
